name: ShopSmart
options:
  bundleIdPrefix: com.shopsmart
  deploymentTarget:
    iOS: "17.0"
targets:
  ShopSmart:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ShopSmart
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shopsmart.ShopSmart
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
schemes:
  ShopSmart:
    build:
      targets:
        ShopSmart: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
