name: ShopSmart
options:
  bundleIdPrefix: com.anil.mukundan
  deploymentTarget:
    iOS: "17.0"
packages:
  FirebaseSDK:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
targets:
  ShopSmart:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ShopSmart
    dependencies:
      - package: FirebaseSDK
        product: FirebaseAuth
      - package: FirebaseSDK
        product: FirebaseFirestore
      - sdk: WatchConnectivity.framework
      - target: ShopSmartWatch
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.anil.mukundan.ShopSmart
        DEVELOPMENT_TEAM: 964Z9H4GC7
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "iPhone Developer"
        Release:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "Apple Distribution"

  ShopSmartWatch:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: ShopSmartWatch
    dependencies:
      - sdk: WatchConnectivity.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.anil.mukundan.ShopSmart.watchkitapp
        DEVELOPMENT_TEAM: 964Z9H4GC7
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: ShopSmart
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "iPhone Developer"
        Release:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "Apple Distribution"
schemes:
  ShopSmart:
    build:
      targets:
        ShopSmart: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
