import SwiftUI

struct StoreFormView: View {
    @Environment(AppDataStore.self) private var dataStore
    @Environment(\.dismiss) private var dismiss

    var store: StoreModel?

    @State private var name = ""
    @State private var notes = ""
    @State private var websiteURL = ""
    @State private var urlIsAutoGenerated = true
    @State private var selectedItemIDs: Set<String> = []
    @State private var showCreateItem = false

    private func autoURL(for name: String) -> String {
        var clean = name.lowercased()
        clean = clean.replacingOccurrences(of: "'", with: "")
        clean = clean.components(separatedBy: .whitespaces).joined()
        return clean.isEmpty ? "" : "https://www.\(clean).com"
    }

    private var isEditing: Bool { store != nil }

    private var allItems: [ItemModel] {
        dataStore.items.sorted { $0.name < $1.name }
    }

    var body: some View {
        NavigationStack {
            Form {
                Section("Store Name") {
                    TextField("e.g. Whole Foods", text: $name)
                }
                Section("Website") {
                    TextField("Enter store URL here", text: $websiteURL)
                        .keyboardType(.URL)
                        .autocorrectionDisabled()
                        .textInputAutocapitalization(.never)
                }
                Section("Notes") {
                    TextField("Optional notes", text: $notes, axis: .vertical)
                        .lineLimit(3...6)
                }
                Section("Items Carried") {
                    Button {
                        showCreateItem = true
                    } label: {
                        Label("Create New Item…", systemImage: "plus.circle")
                    }
                    ForEach(allItems, id: \.id) { item in
                        HStack {
                            Text(item.name)
                            Spacer()
                            if selectedItemIDs.contains(item.id) {
                                Image(systemName: "checkmark")
                                    .foregroundStyle(Color.accentColor)
                                    .fontWeight(.semibold)
                            }
                        }
                        .contentShape(Rectangle())
                        .onTapGesture { toggleItem(item) }
                    }
                }
            }
            .navigationTitle(isEditing ? "Edit Store" : "New Store")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") { save() }
                        .disabled(name.trimmingCharacters(in: .whitespaces).isEmpty)
                }
            }
        }
        .onChange(of: name) { _, newName in
            guard urlIsAutoGenerated else { return }
            websiteURL = autoURL(for: newName)
        }
        .onChange(of: websiteURL) { _, newURL in
            if newURL.isEmpty {
                urlIsAutoGenerated = true
            } else if newURL != autoURL(for: name) {
                urlIsAutoGenerated = false
            }
        }
        .onAppear {
            if let store {
                name = store.name
                notes = store.notes ?? ""
                websiteURL = store.websiteURL ?? ""
                selectedItemIDs = Set(store.itemIDs)
                urlIsAutoGenerated = (store.websiteURL == nil || store.websiteURL == autoURL(for: store.name))
            }
        }
        .sheet(isPresented: $showCreateItem) {
            CreateItemView(
                currentStoreName: name,
                currentStoreID: store?.id
            ) { newItem in
                selectedItemIDs.insert(newItem.id)
            }
        }
    }

    private func save() {
        let trimmedName = name.trimmingCharacters(in: .whitespaces)
        let notesValue = notes.trimmingCharacters(in: .whitespaces)
        let finalNotes = notesValue.isEmpty ? nil : notesValue
        let finalURL = websiteURL.trimmingCharacters(in: .whitespaces)
        let storeURL = finalURL.isEmpty ? nil : finalURL

        if var s = store {
            s.name = trimmedName
            s.notes = finalNotes
            s.websiteURL = storeURL
            s.itemIDs = Array(selectedItemIDs)
            dataStore.updateStore(s)
        } else {
            let newStore = StoreModel(
                name: trimmedName,
                notes: finalNotes,
                websiteURL: storeURL,
                itemIDs: Array(selectedItemIDs)
            )
            dataStore.addStore(newStore)
        }
        dismiss()
    }

    private func toggleItem(_ item: ItemModel) {
        if selectedItemIDs.contains(item.id) {
            selectedItemIDs.remove(item.id)
        } else {
            selectedItemIDs.insert(item.id)
        }
    }
}

#Preview {
    StoreFormView()
        .environment(AppDataStore.preview)
}
