import SwiftUI

struct StoreFormView: View {
    @Environment(AppDataStore.self) private var dataStore
    @Environment(LocationManager.self) private var locationManager
    @Environment(\.dismiss) private var dismiss

    var store: StoreModel?

    @State private var name = ""
    @State private var websiteURL = ""
    @State private var urlIsAutoGenerated = true
    @State private var selectedItemIDs: Set<String> = []
    @State private var locationName: String?
    @State private var latitude: Double?
    @State private var longitude: Double?
    @State private var showLocationPicker = false
    @State private var showLocationPermissionPrompt = false
    @State private var showLocationHelp = false
    @State private var showCreateItem = false
    @FocusState private var nameIsFocused: Bool

    private func autoURL(for name: String) -> String {
        var clean = name.lowercased()
        clean = clean.replacingOccurrences(of: "'", with: "")
        clean = clean.components(separatedBy: .whitespaces).joined()
        return clean.isEmpty ? "" : "https://www.\(clean).com"
    }

    private var isEditing: Bool { store != nil }

    private var allItems: [ItemModel] {
        dataStore.items.sorted { $0.name < $1.name }
    }

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    TextField("e.g. Whole Foods", text: $name)
                        .focused($nameIsFocused)
                } header: {
                    HStack(spacing: 2) {
                        Text("Store Name")
                        Text("*").foregroundStyle(.red)
                    }
                }
                Section {
                    Button {
                        if locationManager.authorizationStatus == .notDetermined {
                            showLocationPermissionPrompt = true
                        } else {
                            showLocationPicker = true
                        }
                    } label: {
                        Label {
                            if let name = locationName {
                                Text(name)
                                    .foregroundStyle(.primary)
                                    .lineLimit(2)
                            } else {
                                Text("Set Location…")
                                    .foregroundStyle(.secondary)
                            }
                        } icon: {
                            Image(systemName: locationName != nil ? "mappin.circle.fill" : "mappin.circle")
                                .foregroundStyle(locationName != nil ? Color.accentColor : Color.secondary)
                        }
                    }
                    .buttonStyle(.plain)
                    if let lat = latitude, let lon = longitude {
                        Button {
                            let url = URL(string: "maps://?ll=\(lat),\(lon)&q=\(name.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? name)")!
                            UIApplication.shared.open(url)
                        } label: {
                            Label("View in Maps", systemImage: "map")
                                .foregroundStyle(Color.accentColor)
                        }
                        Button("Clear Location", role: .destructive) {
                            locationName = nil
                            latitude = nil
                            longitude = nil
                        }
                    }
                } header: {
                    HStack {
                        Text("Location")
                        Button { showLocationHelp = true } label: {
                            Image(systemName: "questionmark.circle")
                                .foregroundStyle(.secondary)
                        }
                        .buttonStyle(.plain)
                    }
                }
                .alert("Location", isPresented: $showLocationHelp) {
                    Button("OK", role: .cancel) { }
                } message: {
                    Text("ShopSmartly uses your location to sort stores by distance and in a future release will alert you when you arrive at a store.")
                }
                Section("Website") {
                    TextField("Enter store URL here", text: $websiteURL)
                        .keyboardType(.URL)
                        .autocorrectionDisabled()
                        .textInputAutocapitalization(.never)
                }
                Section("Items Carried") {
                    Button {
                        showCreateItem = true
                    } label: {
                        Label("Create New Item…", systemImage: "plus.circle")
                    }
                    ForEach(allItems, id: \.id) { item in
                        HStack {
                            Text(item.name)
                            Spacer()
                            if selectedItemIDs.contains(item.id) {
                                Image(systemName: "checkmark")
                                    .foregroundStyle(Color.accentColor)
                                    .fontWeight(.semibold)
                            }
                        }
                        .contentShape(Rectangle())
                        .onTapGesture { toggleItem(item) }
                    }
                }
            }
            .navigationTitle(isEditing ? "Edit Store" : "New Store")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") { save() }
                        .disabled(name.trimmingCharacters(in: .whitespaces).isEmpty)
                }
            }
        }
        .onChange(of: name) { _, newName in
            guard urlIsAutoGenerated else { return }
            websiteURL = autoURL(for: newName)
        }
        .onChange(of: websiteURL) { _, newURL in
            if newURL.isEmpty {
                urlIsAutoGenerated = true
            } else if newURL != autoURL(for: name) {
                urlIsAutoGenerated = false
            }
        }
        .onAppear {
            if let store {
                name = store.name
                websiteURL = store.websiteURL ?? ""
                selectedItemIDs = Set(store.itemIDs)
                urlIsAutoGenerated = (store.websiteURL == nil || store.websiteURL == autoURL(for: store.name))
                locationName = store.locationName
                latitude = store.latitude
                longitude = store.longitude
            } else {
                nameIsFocused = true
            }
        }
        .sheet(isPresented: $showLocationPermissionPrompt, onDismiss: {
            showLocationPicker = true
        }) {
            LocationPermissionPrompt {
                locationManager.requestPermission()
            }
        }
        .sheet(isPresented: $showLocationPicker) {
            LocationPickerSheet(initialQuery: name) { locName, lat, lon in
                locationName = locName
                latitude = lat
                longitude = lon
            }
        }
        .sheet(isPresented: $showCreateItem) {
            CreateItemView(
                currentStoreName: name,
                currentStoreID: store?.id
            ) { newItem in
                selectedItemIDs.insert(newItem.id)
            }
        }
    }

    private func save() {
        let trimmedName = name.trimmingCharacters(in: .whitespaces)
        let finalURL = websiteURL.trimmingCharacters(in: .whitespaces)
        let storeURL = finalURL.isEmpty ? nil : finalURL

        if var s = store {
            s.name = trimmedName
            s.websiteURL = storeURL
            s.itemIDs = Array(selectedItemIDs)
            s.locationName = locationName
            s.latitude = latitude
            s.longitude = longitude
            dataStore.updateStore(s)
        } else {
            let newStore = StoreModel(
                name: trimmedName,
                websiteURL: storeURL,
                itemIDs: Array(selectedItemIDs),
                locationName: locationName,
                latitude: latitude,
                longitude: longitude
            )
            dataStore.addStore(newStore)
        }
        dismiss()
    }

    private func toggleItem(_ item: ItemModel) {
        if selectedItemIDs.contains(item.id) {
            selectedItemIDs.remove(item.id)
        } else {
            selectedItemIDs.insert(item.id)
        }
    }
}

// MARK: - Location Permission Prompt

private struct LocationPermissionPrompt: View {
    let onAllow: () -> Void
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        VStack(spacing: 28) {
            Spacer()
            Image(systemName: "location.circle.fill")
                .font(.system(size: 72))
                .foregroundStyle(Color.appAccent)
            Text("Use Your Location?")
                .font(.title2.weight(.bold))
            Spacer()
            VStack(spacing: 12) {
                Button {
                    onAllow()
                    dismiss()
                } label: {
                    Label("Allow Location Access", systemImage: "location.fill")
                        .frame(maxWidth: .infinity)
                        .fontWeight(.semibold)
                }
                .buttonStyle(.borderedProminent)
                .tint(.appAccent)
                .controlSize(.large)

                Button("Not Now") { dismiss() }
                    .foregroundStyle(.secondary)
            }
            .padding(.horizontal)
            .padding(.bottom)
        }
        .presentationDetents([.medium])
        .presentationDragIndicator(.visible)
    }
}

#Preview {
    StoreFormView()
        .environment(AppDataStore.preview)
        .environment(LocationManager())
}
